# config/_default/languages.en.toml

language = "en"
languageName = "English"
weight = 2
title = "Rafli Ardiansyah"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "Monday, 2 January 2006, 15:04"
description = "Personal site created and maintained by Muhammad Rafli Ardiansyah"

[author]
name = "Muhammad Rafli Ardiansyah"
image = "img/author.jpg"
headline = ""
bio = "Mechatronics Engineer"
links = [
    { email = "mailto:mra53150@gmail.com" },
    { github = "https://github.com/rafliard23" },
    { grabcad = "https://grabcad.com/muhammad.rafli.ardiansyah-1" },
    { instagram = "https://instagram.com/rafli.ard23" }
]