# config/_default/menus.toml

[[main]]
  name = "Post"
  pageRef = "/posts"
  weight = 1

[[main]]
  name = "Project"
  pageRef = "/projects"
  weight = 2

[[main]]
  name = "About"
  pageRef = "/about"
  weight = 3

  [[main]]
  name = "Network"
  url = "http://network.rafliard.net"
  weight = 4